[target.x86_64-unknown-linux-gnu]
# see https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH && apt-get update && apt-get install --assume-yes glib2.0:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH atk1.0:$CROSS_DEB_ARCH libgtk-3-dev:$CROSS_DEB_ARCH"                                 
]
